name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
        cache-dependency-path: ./package-lock.json
    - name: Install
      run: npm ci
    - name: Test units
      run: npm run test:units
    - name: Test interactions
      run: npm run test:interactions
    - name: Test types
      run: npm run test:types
    - name: Test lint
      run: npm run test:lint
    - name: Build application
      run: npm run build
